<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'custo',
  'author' => '',
  'description' => 'Кастомизация контрагентов и контактов для Uclean Group',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Uclean_Group_1',
  'published_date' => '2020-10-14 21:18:12',
  'type' => 'module',
  'version' => 1602710292,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Uclean_Group_1',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'custo_contact',
      'class' => 'custo_contact',
      'path' => 'modules/custo_contact/custo_contact.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'custo_user',
      'class' => 'custo_user',
      'path' => 'modules/custo_user/custo_user.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'custo_company',
      'class' => 'custo_company',
      'path' => 'modules/custo_company/custo_company.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_users_Users.php',
      'to_module' => 'Users',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_securitygroups_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_tasks_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_custo_company_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_calls_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_users_1_Users.php',
      'to_module' => 'Users',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_users_1_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_emails_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_meetings_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_prospectlists_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_incom_incoming_marketing_incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_contact_custo_user.php',
      'to_module' => 'custo_user',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_contact_1_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_contact_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_users_custo_user.php',
      'to_module' => 'custo_user',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_users_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_user_custo_user.php',
      'to_module' => 'custo_user',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_user_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_securitygroups_custo_user.php',
      'to_module' => 'custo_user',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_securitygroups_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_company_custo_user.php',
      'to_module' => 'custo_user',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_custo_company_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_prospectlists_custo_user.php',
      'to_module' => 'custo_user',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_calls_custo_user.php',
      'to_module' => 'custo_user',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_tasks_custo_user.php',
      'to_module' => 'custo_user',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_meetings_custo_user.php',
      'to_module' => 'custo_user',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_emails_custo_user.php',
      'to_module' => 'custo_user',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_emails_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_calls_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_tasks_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_meetings_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_incom_incoming_marketing_custo_user.php',
      'to_module' => 'custo_user',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_user_campaigns_custo_user.php',
      'to_module' => 'custo_user',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_tasks_custo_company.php',
      'to_module' => 'custo_company',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_meetings_custo_company.php',
      'to_module' => 'custo_company',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_calls_custo_company.php',
      'to_module' => 'custo_company',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_emails_custo_company.php',
      'to_module' => 'custo_company',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_users_Users.php',
      'to_module' => 'Users',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_emails_1_Emails.php',
      'to_module' => 'Emails',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_emails_1_custo_company.php',
      'to_module' => 'custo_company',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_securitygroups_custo_company.php',
      'to_module' => 'custo_company',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_prospectlists_custo_company.php',
      'to_module' => 'custo_company',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_custo_contact_custo_company.php',
      'to_module' => 'custo_company',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_custo_contactMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_usersMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_securitygroupsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_tasksMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_custo_companyMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_callsMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_campaignsMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_users_1MetaData.php',
    ),
    8 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_emailsMetaData.php',
    ),
    9 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_meetingsMetaData.php',
    ),
    10 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_prospectlistsMetaData.php',
    ),
    11 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_incom_incoming_marketingMetaData.php',
    ),
    12 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_jjwg_mapsMetaData.php',
    ),
    13 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_custo_contactMetaData.php',
    ),
    14 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_custo_contact_1MetaData.php',
    ),
    15 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_usersMetaData.php',
    ),
    16 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_users_1MetaData.php',
    ),
    17 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_custo_userMetaData.php',
    ),
    18 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_custo_user_1MetaData.php',
    ),
    19 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_securitygroupsMetaData.php',
    ),
    20 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_securitygroups_1MetaData.php',
    ),
    21 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_custo_companyMetaData.php',
    ),
    22 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_custo_company_1MetaData.php',
    ),
    23 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_prospectlistsMetaData.php',
    ),
    24 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_callsMetaData.php',
    ),
    25 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_tasksMetaData.php',
    ),
    26 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_meetingsMetaData.php',
    ),
    27 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_emailsMetaData.php',
    ),
    28 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_emails_1MetaData.php',
    ),
    29 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_calls_1MetaData.php',
    ),
    30 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_tasks_1MetaData.php',
    ),
    31 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_meetings_1MetaData.php',
    ),
    32 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_incom_incoming_marketingMetaData.php',
    ),
    33 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_user_campaignsMetaData.php',
    ),
    34 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_custo_companyMetaData.php',
    ),
    35 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_tasksMetaData.php',
    ),
    36 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_meetingsMetaData.php',
    ),
    37 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_callsMetaData.php',
    ),
    38 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_emailsMetaData.php',
    ),
    39 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_usersMetaData.php',
    ),
    40 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_emails_1MetaData.php',
    ),
    41 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_securitygroupsMetaData.php',
    ),
    42 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_prospectlistsMetaData.php',
    ),
    43 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_jjwg_mapsMetaData.php',
    ),
    44 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_campaignsMetaData.php',
    ),
    45 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_custo_contactMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/custo_contact',
      'to' => 'modules/custo_contact',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/custo_user',
      'to' => 'modules/custo_user',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/custo_company',
      'to' => 'modules/custo_company',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_RU',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'ru_RU',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'ru_RU',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'ru_RU',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'en_us',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'ru_RU',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
      'language' => 'en_us',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
      'language' => 'ru_RU',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'en_us',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'ru_RU',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_RU',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_RU',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'en_us',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'ru_RU',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'ru_RU',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'ru_RU',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'ru_RU',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'ru_RU',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    121 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    122 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
      'language' => 'en_us',
    ),
    123 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
      'language' => 'ru_RU',
    ),
    124 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    125 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    126 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'en_us',
    ),
    127 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'ru_RU',
    ),
    128 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'en_us',
    ),
    129 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_user.php',
      'to_module' => 'custo_user',
      'language' => 'ru_RU',
    ),
    130 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    131 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    132 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    133 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'ru_RU',
    ),
    134 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    135 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    136 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    137 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    138 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    139 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    140 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    141 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'ru_RU',
    ),
    142 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    143 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    144 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    145 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    146 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    147 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    148 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    149 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    150 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    151 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    152 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    153 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    154 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    155 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    156 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    157 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_RU',
    ),
    158 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    159 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    160 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'en_us',
    ),
    161 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'ru_RU',
    ),
    162 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    163 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    164 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    165 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    166 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'en_us',
    ),
    167 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'ru_RU',
    ),
    168 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    169 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    170 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'en_us',
    ),
    171 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'ru_RU',
    ),
    172 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    173 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    174 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    175 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    176 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    177 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ru_RU.lang.php',
      'to_module' => 'application',
      'language' => 'ru_RU',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_Users.php',
      'to_module' => 'Users',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_securitygroups_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_tasks_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_custo_company_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_calls_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_campaigns_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_1_Users.php',
      'to_module' => 'Users',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_1_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_emails_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_meetings_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_prospectlists_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_incom_incoming_marketing_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_incom_incoming_marketing_incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_jjwg_maps_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_contact_custo_user.php',
      'to_module' => 'custo_user',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_contact_1_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_contact_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_users_Users.php',
      'to_module' => 'Users',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_users_custo_user.php',
      'to_module' => 'custo_user',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_users_1_Users.php',
      'to_module' => 'Users',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_users_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_user_custo_user.php',
      'to_module' => 'custo_user',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_user_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_securitygroups_custo_user.php',
      'to_module' => 'custo_user',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_securitygroups_1_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_securitygroups_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_company_custo_user.php',
      'to_module' => 'custo_user',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_company_1_custo_company.php',
      'to_module' => 'custo_company',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_custo_company_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_prospectlists_custo_user.php',
      'to_module' => 'custo_user',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_calls_custo_user.php',
      'to_module' => 'custo_user',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_tasks_custo_user.php',
      'to_module' => 'custo_user',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_meetings_custo_user.php',
      'to_module' => 'custo_user',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_emails_custo_user.php',
      'to_module' => 'custo_user',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_emails_1_Emails.php',
      'to_module' => 'Emails',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_emails_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_calls_1_Calls.php',
      'to_module' => 'Calls',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_calls_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_tasks_1_Tasks.php',
      'to_module' => 'Tasks',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_tasks_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_meetings_1_Meetings.php',
      'to_module' => 'Meetings',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_meetings_1_custo_user.php',
      'to_module' => 'custo_user',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_incom_incoming_marketing_incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_incom_incoming_marketing_custo_user.php',
      'to_module' => 'custo_user',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_user_campaigns_custo_user.php',
      'to_module' => 'custo_user',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_tasks_custo_company.php',
      'to_module' => 'custo_company',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_meetings_custo_company.php',
      'to_module' => 'custo_company',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_calls_custo_company.php',
      'to_module' => 'custo_company',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_custo_company.php',
      'to_module' => 'custo_company',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_users_custo_company.php',
      'to_module' => 'custo_company',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_users_Users.php',
      'to_module' => 'Users',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_1_Emails.php',
      'to_module' => 'Emails',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_1_custo_company.php',
      'to_module' => 'custo_company',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_securitygroups_custo_company.php',
      'to_module' => 'custo_company',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_prospectlists_custo_company.php',
      'to_module' => 'custo_company',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_jjwg_maps_custo_company.php',
      'to_module' => 'custo_company',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_campaigns_custo_company.php',
      'to_module' => 'custo_company',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_custo_contact_custo_company.php',
      'to_module' => 'custo_company',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'custo_contact' => 'custo_contact_custo_contact_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'custo_contact' => 'custo_contact_users_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'custo_contact_tasks_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'custo_contact' => 'custo_contact_campaigns_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
        'custo_contact' => 'custo_contact_incom_incoming_marketing_name',
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
        'custo_contact' => 'custo_contact_jjwg_maps_name',
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
        'custo_contact' => 'custo_user_custo_contact_name',
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'custo_user_users_name',
      ),
    ),
    8 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'custo_user_users_1_name',
      ),
    ),
    9 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    10 => 
    array (
      'additional_fields' => 
      array (
        'SecurityGroups' => 'custo_user_securitygroups_1_name',
      ),
    ),
    11 => 
    array (
      'additional_fields' => 
      array (
        'custo_company' => 'custo_user_custo_company_1_name',
      ),
    ),
    12 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    13 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'custo_user_calls_1_name',
      ),
    ),
    14 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'custo_user_tasks_1_name',
      ),
    ),
    15 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'custo_user_meetings_1_name',
      ),
    ),
    16 => 
    array (
      'additional_fields' => 
      array (
        'incom_incoming_marketing' => 'custo_user_incom_incoming_marketing_name',
      ),
    ),
    17 => 
    array (
      'additional_fields' => 
      array (
        'Campaigns' => 'custo_user_campaigns_name',
      ),
    ),
    18 => 
    array (
      'additional_fields' => 
      array (
        'custo_company' => 'custo_company_custo_company_name',
      ),
    ),
    19 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'custo_company_tasks_name',
      ),
    ),
    20 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'custo_company_meetings_name',
      ),
    ),
    21 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'custo_company_calls_name',
      ),
    ),
    22 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    23 => 
    array (
      'additional_fields' => 
      array (
        'custo_company' => 'custo_company_users_name',
      ),
    ),
    24 => 
    array (
      'additional_fields' => 
      array (
        'custo_company' => 'custo_company_jjwg_maps_name',
      ),
    ),
    25 => 
    array (
      'additional_fields' => 
      array (
        'custo_company' => 'custo_company_campaigns_name',
      ),
    ),
  ),
);