<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'custo',
  'author' => '',
  'description' => 'Кастомизация контрагентов и контактов для Uclean Group',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Example',
  'published_date' => '2020-10-13 19:41:44',
  'type' => 'module',
  'version' => 1602618104,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Example',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'custo_contact',
      'class' => 'custo_contact',
      'path' => 'modules/custo_contact/custo_contact.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'custo_company',
      'class' => 'custo_company',
      'path' => 'modules/custo_company/custo_company.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_users_Users.php',
      'to_module' => 'Users',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_securitygroups_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_tasks_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_custo_company_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_calls_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_users_1_Users.php',
      'to_module' => 'Users',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_users_1_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_emails_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_meetings_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_prospectlists_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_incom_incoming_marketing_incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_contact_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_tasks_custo_company.php',
      'to_module' => 'custo_company',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_meetings_custo_company.php',
      'to_module' => 'custo_company',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_calls_custo_company.php',
      'to_module' => 'custo_company',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_emails_custo_company.php',
      'to_module' => 'custo_company',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_users_Users.php',
      'to_module' => 'Users',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_emails_1_Emails.php',
      'to_module' => 'Emails',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_emails_1_custo_company.php',
      'to_module' => 'custo_company',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_securitygroups_custo_company.php',
      'to_module' => 'custo_company',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_prospectlists_custo_company.php',
      'to_module' => 'custo_company',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/custo_company_custo_contact_custo_company.php',
      'to_module' => 'custo_company',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_custo_contactMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_usersMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_securitygroupsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_tasksMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_custo_companyMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_callsMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_campaignsMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_users_1MetaData.php',
    ),
    8 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_emailsMetaData.php',
    ),
    9 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_meetingsMetaData.php',
    ),
    10 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_prospectlistsMetaData.php',
    ),
    11 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_incom_incoming_marketingMetaData.php',
    ),
    12 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_contact_jjwg_mapsMetaData.php',
    ),
    13 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_custo_companyMetaData.php',
    ),
    14 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_tasksMetaData.php',
    ),
    15 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_meetingsMetaData.php',
    ),
    16 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_callsMetaData.php',
    ),
    17 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_emailsMetaData.php',
    ),
    18 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_usersMetaData.php',
    ),
    19 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_emails_1MetaData.php',
    ),
    20 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_securitygroupsMetaData.php',
    ),
    21 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_prospectlistsMetaData.php',
    ),
    22 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_jjwg_mapsMetaData.php',
    ),
    23 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_campaignsMetaData.php',
    ),
    24 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/custo_company_custo_contactMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/custo_contact',
      'to' => 'modules/custo_contact',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/custo_company',
      'to' => 'modules/custo_company',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_RU',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'ru_RU',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'ru_RU',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'ru_RU',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'en_us',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'ru_RU',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
      'language' => 'en_us',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
      'language' => 'ru_RU',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'en_us',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'ru_RU',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'ru_RU',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'ru_RU',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'ru_RU',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'en_us',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/SecurityGroups.php',
      'to_module' => 'SecurityGroups',
      'language' => 'ru_RU',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'en_us',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ProspectLists.php',
      'to_module' => 'ProspectLists',
      'language' => 'ru_RU',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'en_us',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'ru_RU',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'en_us',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Campaigns.php',
      'to_module' => 'Campaigns',
      'language' => 'ru_RU',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'en_us',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_contact.php',
      'to_module' => 'custo_contact',
      'language' => 'ru_RU',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'en_us',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/custo_company.php',
      'to_module' => 'custo_company',
      'language' => 'ru_RU',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ru_RU.lang.php',
      'to_module' => 'application',
      'language' => 'ru_RU',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_Users.php',
      'to_module' => 'Users',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_securitygroups_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_tasks_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_custo_company_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_calls_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_campaigns_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_1_Users.php',
      'to_module' => 'Users',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_users_1_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_emails_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_meetings_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_prospectlists_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_incom_incoming_marketing_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_incom_incoming_marketing_incom_incoming_marketing.php',
      'to_module' => 'incom_incoming_marketing',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_jjwg_maps_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_contact_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_custo_company_custo_company.php',
      'to_module' => 'custo_company',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_tasks_custo_company.php',
      'to_module' => 'custo_company',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_meetings_custo_company.php',
      'to_module' => 'custo_company',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_calls_custo_company.php',
      'to_module' => 'custo_company',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_custo_company.php',
      'to_module' => 'custo_company',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_users_custo_company.php',
      'to_module' => 'custo_company',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_users_Users.php',
      'to_module' => 'Users',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_1_Emails.php',
      'to_module' => 'Emails',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_emails_1_custo_company.php',
      'to_module' => 'custo_company',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_securitygroups_SecurityGroups.php',
      'to_module' => 'SecurityGroups',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_securitygroups_custo_company.php',
      'to_module' => 'custo_company',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_prospectlists_ProspectLists.php',
      'to_module' => 'ProspectLists',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_prospectlists_custo_company.php',
      'to_module' => 'custo_company',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_jjwg_maps_custo_company.php',
      'to_module' => 'custo_company',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_jjwg_maps_jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_campaigns_custo_company.php',
      'to_module' => 'custo_company',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_campaigns_Campaigns.php',
      'to_module' => 'Campaigns',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_custo_contact_custo_contact.php',
      'to_module' => 'custo_contact',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/custo_company_custo_contact_custo_company.php',
      'to_module' => 'custo_company',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'custo_contact_tasks_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'custo_company_tasks_name',
      ),
    ),
    8 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'custo_company_meetings_name',
      ),
    ),
    9 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'custo_company_calls_name',
      ),
    ),
    10 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    11 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    12 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    13 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);