<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'custo_contact_prospectlists' => 
  array (
    'id' => '12b4cad4-cfd2-6c26-61e7-5f897e942a4a',
    'relationship_name' => 'custo_contact_prospectlists',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'ProspectLists',
    'rhs_table' => 'prospect_lists',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_prospectlists_c',
    'join_key_lhs' => 'custo_contact_prospectlistscusto_contact_ida',
    'join_key_rhs' => 'custo_contact_prospectlistsprospectlists_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_custo_company' => 
  array (
    'id' => '132a7380-55ff-51e2-9910-5f897ee62bca',
    'relationship_name' => 'custo_contact_custo_company',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_company',
    'rhs_table' => 'custo_company',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_custo_company_c',
    'join_key_lhs' => 'custo_contact_custo_companycusto_contact_ida',
    'join_key_rhs' => 'custo_contact_custo_companycusto_company_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_custo_contact' => 
  array (
    'id' => '14d18f1c-96a8-f43d-9207-5f897e902a3c',
    'relationship_name' => 'custo_contact_custo_contact',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_custo_contact_c',
    'join_key_lhs' => 'custo_contact_custo_contactcusto_contact_ida',
    'join_key_rhs' => 'custo_contact_custo_contactcusto_contact_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_company_custo_contact' => 
  array (
    'id' => '1a6c0c82-6876-189f-aaae-5f897ebe6e60',
    'relationship_name' => 'custo_company_custo_contact',
    'lhs_module' => 'custo_company',
    'lhs_table' => 'custo_company',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_company_custo_contact_c',
    'join_key_lhs' => 'custo_company_custo_contactcusto_company_ida',
    'join_key_rhs' => 'custo_company_custo_contactcusto_contact_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_incom_incoming_marketing' => 
  array (
    'id' => '3f720809-2f24-6d60-86a8-5f897e7fe6fa',
    'relationship_name' => 'custo_contact_incom_incoming_marketing',
    'lhs_module' => 'incom_incoming_marketing',
    'lhs_table' => 'incom_incoming_marketing',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_incom_incoming_marketing_c',
    'join_key_lhs' => 'custo_contf866rketing_ida',
    'join_key_rhs' => 'custo_contact_incom_incoming_marketingcusto_contact_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_calls' => 
  array (
    'id' => '46a90a43-5b1c-1188-d91e-5f897e9d7a69',
    'relationship_name' => 'custo_contact_calls',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_calls_c',
    'join_key_lhs' => 'custo_contact_callscusto_contact_ida',
    'join_key_rhs' => 'custo_contact_callscalls_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_tasks' => 
  array (
    'id' => '93d104c7-da1a-865e-b2fc-5f897e816b66',
    'relationship_name' => 'custo_contact_tasks',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_tasks_c',
    'join_key_lhs' => 'custo_contact_taskscusto_contact_ida',
    'join_key_rhs' => 'custo_contact_taskstasks_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_modified_user' => 
  array (
    'id' => '98f124ee-50c7-c15e-4514-5f897e08cece',
    'relationship_name' => 'custo_contact_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'custo_contact_created_by' => 
  array (
    'id' => '99d79cad-1f03-4b61-496b-5f897e6eb53d',
    'relationship_name' => 'custo_contact_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'custo_contact_assigned_user' => 
  array (
    'id' => '9aae920c-9289-7e3f-4b02-5f897ef33ba3',
    'relationship_name' => 'custo_contact_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_custo_contact' => 
  array (
    'id' => '9b8526ec-0833-47a0-0bad-5f897eb9f047',
    'relationship_name' => 'securitygroups_custo_contact',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'custo_contact',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'custo_user_custo_contact_1' => 
  array (
    'id' => 'c177050d-242e-dd47-66a8-5f897e85f9dc',
    'relationship_name' => 'custo_user_custo_contact_1',
    'lhs_module' => 'custo_user',
    'lhs_table' => 'custo_user',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_user_custo_contact_1_c',
    'join_key_lhs' => 'custo_user_custo_contact_1custo_user_ida',
    'join_key_rhs' => 'custo_user_custo_contact_1custo_contact_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_emails' => 
  array (
    'id' => 'dbd002e0-432a-d792-0a4e-5f897e9ae291',
    'relationship_name' => 'custo_contact_emails',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_emails_c',
    'join_key_lhs' => 'custo_contact_emailscusto_contact_ida',
    'join_key_rhs' => 'custo_contact_emailsemails_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForQueues',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_jjwg_maps' => 
  array (
    'id' => 'e6f41bd8-1056-1b98-d65d-5f897e4e6977',
    'relationship_name' => 'custo_contact_jjwg_maps',
    'lhs_module' => 'jjwg_Maps',
    'lhs_table' => 'jjwg_maps',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_jjwg_maps_c',
    'join_key_lhs' => 'custo_contact_jjwg_mapsjjwg_maps_ida',
    'join_key_rhs' => 'custo_contact_jjwg_mapscusto_contact_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_securitygroups' => 
  array (
    'id' => 'e88c8dff-ba4b-4224-fdb5-5f897e5792fa',
    'relationship_name' => 'custo_contact_securitygroups',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'SecurityGroups',
    'rhs_table' => 'securitygroups',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_securitygroups_c',
    'join_key_lhs' => 'custo_contact_securitygroupscusto_contact_ida',
    'join_key_rhs' => 'custo_contact_securitygroupssecuritygroups_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_meetings' => 
  array (
    'id' => 'ea98e6e0-bb39-7c4b-e952-5f897ec5b34b',
    'relationship_name' => 'custo_contact_meetings',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_meetings_c',
    'join_key_lhs' => 'custo_contact_meetingscusto_contact_ida',
    'join_key_rhs' => 'custo_contact_meetingsmeetings_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_users_1' => 
  array (
    'id' => 'edca8b14-67db-0a0d-7f72-5f897eed9cf5',
    'relationship_name' => 'custo_contact_users_1',
    'lhs_module' => 'custo_contact',
    'lhs_table' => 'custo_contact',
    'lhs_key' => 'id',
    'rhs_module' => 'Users',
    'rhs_table' => 'users',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_users_1_c',
    'join_key_lhs' => 'custo_contact_users_1custo_contact_ida',
    'join_key_rhs' => 'custo_contact_users_1users_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_user_custo_contact' => 
  array (
    'id' => 'f1cc3a70-be2e-209d-3d0b-5f897ea5052b',
    'relationship_name' => 'custo_user_custo_contact',
    'lhs_module' => 'custo_user',
    'lhs_table' => 'custo_user',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_user_custo_contact_c',
    'join_key_lhs' => 'custo_user_custo_contactcusto_user_ida',
    'join_key_rhs' => 'custo_user_custo_contactcusto_contact_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_users' => 
  array (
    'id' => 'f3527d8b-0117-e7ce-8770-5f897e3e52a6',
    'relationship_name' => 'custo_contact_users',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_users_c',
    'join_key_lhs' => 'custo_contact_usersusers_ida',
    'join_key_rhs' => 'custo_contact_userscusto_contact_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_campaigns' => 
  array (
    'id' => 'fe31039a-7d59-6fd2-5cef-5f897e72d992',
    'relationship_name' => 'custo_contact_campaigns',
    'lhs_module' => 'Campaigns',
    'lhs_table' => 'campaigns',
    'lhs_key' => 'id',
    'rhs_module' => 'custo_contact',
    'rhs_table' => 'custo_contact',
    'rhs_key' => 'id',
    'join_table' => 'custo_contact_campaigns_c',
    'join_key_lhs' => 'custo_contact_campaignscampaigns_ida',
    'join_key_rhs' => 'custo_contact_campaignscusto_contact_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'custo_contact_custo_company_1' => 
  array (
    'lhs_module' => 'custo_contact',
    'rhs_module' => 'custo_company',
    'relationship_type' => 'one-to-one',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'custo_contact_custo_company_1',
  ),
);