<?php /* Smarty version 2.6.31, created on 2020-06-17 15:31:13
         compiled from custom/modules/Configurator/asterisk_configurator_table.tpl */ ?>
<!-- THIS FILE IS AUTOGENERATED BY RUNNING configuratorGeneratorUtil > asterisk_configurator_table.tpl -->

<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>License</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LICENSE']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_LICENSE_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LICENSE_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_license'] )): ?>
        <?php $this->assign('asterisk_license', $this->_tpl_vars['asterisk_config']['asterisk_license']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_license', $this->_tpl_vars['config']['asterisk_license']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_license' size="45" value='<?php echo $this->_tpl_vars['asterisk_license']; ?>
'>
    </td>

<TD>&nbsp;</TD><TD>&nbsp;</TD> </tr>

<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Asterisk Server Settings</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_HOST']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_HOST_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_HOST_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_host'] )): ?>
        <?php $this->assign('asterisk_host', $this->_tpl_vars['asterisk_config']['asterisk_host']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_host', $this->_tpl_vars['config']['asterisk_host']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_host' size="45" value='<?php echo $this->_tpl_vars['asterisk_host']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_PORT']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_PORT_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_PORT_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_port'] )): ?>
        <?php $this->assign('asterisk_port', $this->_tpl_vars['asterisk_config']['asterisk_port']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_port', $this->_tpl_vars['config']['asterisk_port']); ?>
    <?php endif; ?>
        <input type='int' name='asterisk_port' size="45" value='<?php echo $this->_tpl_vars['asterisk_port']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_USER']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_USER_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_USER_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_user'] )): ?>
        <?php $this->assign('asterisk_user', $this->_tpl_vars['asterisk_config']['asterisk_user']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_user', $this->_tpl_vars['config']['asterisk_user']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_user' size="45" value='<?php echo $this->_tpl_vars['asterisk_user']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SECRET']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_SECRET_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SECRET_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_secret'] )): ?>
        <?php $this->assign('asterisk_secret', $this->_tpl_vars['asterisk_config']['asterisk_secret']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_secret', $this->_tpl_vars['config']['asterisk_secret']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_secret' size="45" value='<?php echo $this->_tpl_vars['asterisk_secret']; ?>
'>
    </td>



<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>SugarCRM SOAP Settings</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SOAPUSER']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_SOAPUSER_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SOAPUSER_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_soapuser'] )): ?>
        <?php $this->assign('asterisk_soapuser', $this->_tpl_vars['asterisk_config']['asterisk_soapuser']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_soapuser', $this->_tpl_vars['config']['asterisk_soapuser']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_soapuser' size="45" value='<?php echo $this->_tpl_vars['asterisk_soapuser']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SOAPPASS']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_SOAPPASS_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SOAPPASS_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_soappass'] )): ?>
        <?php $this->assign('asterisk_soappass', $this->_tpl_vars['asterisk_config']['asterisk_soappass']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_soappass', $this->_tpl_vars['config']['asterisk_soappass']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_soappass' size="45" value='<?php echo $this->_tpl_vars['asterisk_soappass']; ?>
'>
    </td>



<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Call Configuration</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_PREFIX']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_PREFIX_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_PREFIX_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_prefix'] )): ?>
        <?php $this->assign('asterisk_prefix', $this->_tpl_vars['asterisk_config']['asterisk_prefix']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_prefix', $this->_tpl_vars['config']['asterisk_prefix']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_prefix' size="45" value='<?php echo $this->_tpl_vars['asterisk_prefix']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALINPREFIX']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALINPREFIX_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALINPREFIX_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_dialinPrefix'] )): ?>
        <?php $this->assign('asterisk_dialinPrefix', $this->_tpl_vars['asterisk_config']['asterisk_dialinPrefix']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_dialinPrefix', $this->_tpl_vars['config']['asterisk_dialinPrefix']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_dialinPrefix' size="45" value='<?php echo $this->_tpl_vars['asterisk_dialinPrefix']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CONTEXT']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CONTEXT_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CONTEXT_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_context'] )): ?>
        <?php $this->assign('asterisk_context', $this->_tpl_vars['asterisk_config']['asterisk_context']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_context', $this->_tpl_vars['config']['asterisk_context']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_context' size="45" value='<?php echo $this->_tpl_vars['asterisk_context']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_EXPR']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_EXPR_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_EXPR_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_expr'] )): ?>
        <?php $this->assign('asterisk_expr', $this->_tpl_vars['asterisk_config']['asterisk_expr']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_expr', $this->_tpl_vars['config']['asterisk_expr']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_expr' size="45" value='<?php echo $this->_tpl_vars['asterisk_expr']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALOUT_CHANNEL']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALOUT_CHANNEL_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALOUT_CHANNEL_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_dialout_channel'] )): ?>
        <?php $this->assign('asterisk_dialout_channel', $this->_tpl_vars['asterisk_config']['asterisk_dialout_channel']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_dialout_channel', $this->_tpl_vars['config']['asterisk_dialout_channel']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_dialout_channel' size="45" value='<?php echo $this->_tpl_vars['asterisk_dialout_channel']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALIN_EXT_MATCH']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALIN_EXT_MATCH_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIALIN_EXT_MATCH_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_dialin_ext_match'] )): ?>
        <?php $this->assign('asterisk_dialin_ext_match', $this->_tpl_vars['asterisk_config']['asterisk_dialin_ext_match']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_dialin_ext_match', $this->_tpl_vars['config']['asterisk_dialin_ext_match']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_dialin_ext_match' size="45" value='<?php echo $this->_tpl_vars['asterisk_dialin_ext_match']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RG_DETECT_EXPR']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_RG_DETECT_EXPR_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RG_DETECT_EXPR_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_rg_detect_expr'] )): ?>
        <?php $this->assign('asterisk_rg_detect_expr', $this->_tpl_vars['asterisk_config']['asterisk_rg_detect_expr']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_rg_detect_expr', $this->_tpl_vars['config']['asterisk_rg_detect_expr']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_rg_detect_expr' size="45" value='<?php echo $this->_tpl_vars['asterisk_rg_detect_expr']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RG_CELL_RING_EXPR']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_RG_CELL_RING_EXPR_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RG_CELL_RING_EXPR_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_rg_cell_ring_expr'] )): ?>
        <?php $this->assign('asterisk_rg_cell_ring_expr', $this->_tpl_vars['asterisk_config']['asterisk_rg_cell_ring_expr']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_rg_cell_ring_expr', $this->_tpl_vars['config']['asterisk_rg_cell_ring_expr']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_rg_cell_ring_expr' size="45" value='<?php echo $this->_tpl_vars['asterisk_rg_cell_ring_expr']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIGITS_TO_MATCH']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_DIGITS_TO_MATCH_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_DIGITS_TO_MATCH_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_digits_to_match'] )): ?>
        <?php $this->assign('asterisk_digits_to_match', $this->_tpl_vars['asterisk_config']['asterisk_digits_to_match']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_digits_to_match', $this->_tpl_vars['config']['asterisk_digits_to_match']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_digits_to_match' size="45" value='<?php echo $this->_tpl_vars['asterisk_digits_to_match']; ?>
'>
    </td>

<TD>&nbsp;</TD><TD>&nbsp;</TD> </tr>

<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Misc</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_INBOUND_ABBR']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_INBOUND_ABBR_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_INBOUND_ABBR_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_call_subject_inbound_abbr'] )): ?>
        <?php $this->assign('asterisk_call_subject_inbound_abbr', $this->_tpl_vars['asterisk_config']['asterisk_call_subject_inbound_abbr']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_call_subject_inbound_abbr', $this->_tpl_vars['config']['asterisk_call_subject_inbound_abbr']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_call_subject_inbound_abbr' size="45" value='<?php echo $this->_tpl_vars['asterisk_call_subject_inbound_abbr']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_OUTBOUND_ABBR']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_OUTBOUND_ABBR_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_OUTBOUND_ABBR_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_call_subject_outbound_abbr'] )): ?>
        <?php $this->assign('asterisk_call_subject_outbound_abbr', $this->_tpl_vars['asterisk_config']['asterisk_call_subject_outbound_abbr']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_call_subject_outbound_abbr', $this->_tpl_vars['config']['asterisk_call_subject_outbound_abbr']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_call_subject_outbound_abbr' size="45" value='<?php echo $this->_tpl_vars['asterisk_call_subject_outbound_abbr']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_MAX_LENGTH']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_MAX_LENGTH_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALL_SUBJECT_MAX_LENGTH_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_call_subject_max_length'] )): ?>
        <?php $this->assign('asterisk_call_subject_max_length', $this->_tpl_vars['asterisk_config']['asterisk_call_subject_max_length']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_call_subject_max_length', $this->_tpl_vars['config']['asterisk_call_subject_max_length']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_call_subject_max_length' size="45" value='<?php echo $this->_tpl_vars['asterisk_call_subject_max_length']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LISTENER_POLL_RATE']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_LISTENER_POLL_RATE_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LISTENER_POLL_RATE_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_listener_poll_rate'] )): ?>
        <?php $this->assign('asterisk_listener_poll_rate', $this->_tpl_vars['asterisk_config']['asterisk_listener_poll_rate']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_listener_poll_rate', $this->_tpl_vars['config']['asterisk_listener_poll_rate']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_listener_poll_rate' size="45" value='<?php echo $this->_tpl_vars['asterisk_listener_poll_rate']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SHORT_CALL_STATUS']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_SHORT_CALL_STATUS_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_SHORT_CALL_STATUS_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_short_call_status'] )): ?>
        <?php $this->assign('asterisk_short_call_status', $this->_tpl_vars['asterisk_config']['asterisk_short_call_status']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_short_call_status', $this->_tpl_vars['config']['asterisk_short_call_status']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_short_call_status' size="45" value='<?php echo $this->_tpl_vars['asterisk_short_call_status']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_HIDE_CALL_POPUPS_AFTER_MINS']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_HIDE_CALL_POPUPS_AFTER_MINS_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_HIDE_CALL_POPUPS_AFTER_MINS_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_hide_call_popups_after_mins'] )): ?>
        <?php $this->assign('asterisk_hide_call_popups_after_mins', $this->_tpl_vars['asterisk_config']['asterisk_hide_call_popups_after_mins']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_hide_call_popups_after_mins', $this->_tpl_vars['config']['asterisk_hide_call_popups_after_mins']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_hide_call_popups_after_mins' size="45" value='<?php echo $this->_tpl_vars['asterisk_hide_call_popups_after_mins']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_JQUERY_OVERRIDE']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_JQUERY_OVERRIDE_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_JQUERY_OVERRIDE_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_jquery_override'] )): ?>
        <?php $this->assign('asterisk_jquery_override', $this->_tpl_vars['asterisk_config']['asterisk_jquery_override']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_jquery_override'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_jquery_override', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_jquery_override', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_jquery_override', ''); ?>
            <?php $this->assign('caseNumasterisk_jquery_override', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_jquery_override', $this->_tpl_vars['config']['asterisk_jquery_override']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_jquery_override'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_jquery_override', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_jquery_override', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_jquery_override', ''); ?>
            <?php $this->assign('caseNumasterisk_jquery_override', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_jquery_override' value='0'>
    <input type='checkbox' name='asterisk_jquery_override' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_jquery_override']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_jquery_override']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_jquery_override']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_jquery_override']; ?>
' -->
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_MAX_POPUPS']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_MAX_POPUPS_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_MAX_POPUPS_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_max_popups'] )): ?>
        <?php $this->assign('asterisk_max_popups', $this->_tpl_vars['asterisk_config']['asterisk_max_popups']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_max_popups', $this->_tpl_vars['config']['asterisk_max_popups']); ?>
    <?php endif; ?>
        <input type='int' name='asterisk_max_popups' size="45" value='<?php echo $this->_tpl_vars['asterisk_max_popups']; ?>
'>
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LOGGER_SQL_MODE']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_LOGGER_SQL_MODE_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LOGGER_SQL_MODE_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_logger_sql_mode'] )): ?>
        <?php $this->assign('asterisk_logger_sql_mode', $this->_tpl_vars['asterisk_config']['asterisk_logger_sql_mode']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_logger_sql_mode'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_logger_sql_mode', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_logger_sql_mode', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_logger_sql_mode', ''); ?>
            <?php $this->assign('caseNumasterisk_logger_sql_mode', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_logger_sql_mode', $this->_tpl_vars['config']['asterisk_logger_sql_mode']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_logger_sql_mode'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_logger_sql_mode', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_logger_sql_mode', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_logger_sql_mode', ''); ?>
            <?php $this->assign('caseNumasterisk_logger_sql_mode', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_logger_sql_mode' value='0'>
    <input type='checkbox' name='asterisk_logger_sql_mode' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_logger_sql_mode']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_logger_sql_mode']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_logger_sql_mode']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_logger_sql_mode']; ?>
' -->
    </td>

<TD>&nbsp;</TD><TD>&nbsp;</TD> </tr>

<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Logging</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LOG_FILE']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_LOG_FILE_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_LOG_FILE_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_log_file'] )): ?>
        <?php $this->assign('asterisk_log_file', $this->_tpl_vars['asterisk_config']['asterisk_log_file']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_log_file', $this->_tpl_vars['config']['asterisk_log_file']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_log_file' size="45" value='<?php echo $this->_tpl_vars['asterisk_log_file']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_EVENT_LOG_FILE']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_EVENT_LOG_FILE_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_EVENT_LOG_FILE_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_event_log_file'] )): ?>
        <?php $this->assign('asterisk_event_log_file', $this->_tpl_vars['asterisk_config']['asterisk_event_log_file']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_event_log_file', $this->_tpl_vars['config']['asterisk_event_log_file']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_event_log_file' size="45" value='<?php echo $this->_tpl_vars['asterisk_event_log_file']; ?>
'>
    </td>



<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Popup UI</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_BLOCK_BUTTON_ENABLED']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_BLOCK_BUTTON_ENABLED_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_BLOCK_BUTTON_ENABLED_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_block_button_enabled'] )): ?>
        <?php $this->assign('asterisk_block_button_enabled', $this->_tpl_vars['asterisk_config']['asterisk_block_button_enabled']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_block_button_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_block_button_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_block_button_enabled', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_block_button_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_block_button_enabled', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_block_button_enabled', $this->_tpl_vars['config']['asterisk_block_button_enabled']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_block_button_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_block_button_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_block_button_enabled', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_block_button_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_block_button_enabled', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_block_button_enabled' value='0'>
    <input type='checkbox' name='asterisk_block_button_enabled' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_block_button_enabled']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_block_button_enabled']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_block_button_enabled']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_block_button_enabled']; ?>
' -->
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_TRANSFER_BUTTON_ENABLED']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_TRANSFER_BUTTON_ENABLED_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_TRANSFER_BUTTON_ENABLED_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_transfer_button_enabled'] )): ?>
        <?php $this->assign('asterisk_transfer_button_enabled', $this->_tpl_vars['asterisk_config']['asterisk_transfer_button_enabled']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_transfer_button_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_transfer_button_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_transfer_button_enabled', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_transfer_button_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_transfer_button_enabled', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_transfer_button_enabled', $this->_tpl_vars['config']['asterisk_transfer_button_enabled']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_transfer_button_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_transfer_button_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_transfer_button_enabled', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_transfer_button_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_transfer_button_enabled', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_transfer_button_enabled' value='0'>
    <input type='checkbox' name='asterisk_transfer_button_enabled' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_transfer_button_enabled']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_transfer_button_enabled']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_transfer_button_enabled']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_transfer_button_enabled']; ?>
' -->
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RELATE_TO_ACCOUNT_ENABLED']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_RELATE_TO_ACCOUNT_ENABLED_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RELATE_TO_ACCOUNT_ENABLED_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_relate_to_account_enabled'] )): ?>
        <?php $this->assign('asterisk_relate_to_account_enabled', $this->_tpl_vars['asterisk_config']['asterisk_relate_to_account_enabled']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_relate_to_account_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_relate_to_account_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_relate_to_account_enabled', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_relate_to_account_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_relate_to_account_enabled', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_relate_to_account_enabled', $this->_tpl_vars['config']['asterisk_relate_to_account_enabled']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_relate_to_account_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_relate_to_account_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_relate_to_account_enabled', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_relate_to_account_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_relate_to_account_enabled', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_relate_to_account_enabled' value='0'>
    <input type='checkbox' name='asterisk_relate_to_account_enabled' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_relate_to_account_enabled']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_relate_to_account_enabled']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_relate_to_account_enabled']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_relate_to_account_enabled']; ?>
' -->
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RELATE_TO_CONTACT_ENABLED']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_RELATE_TO_CONTACT_ENABLED_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_RELATE_TO_CONTACT_ENABLED_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_relate_to_contact_enabled'] )): ?>
        <?php $this->assign('asterisk_relate_to_contact_enabled', $this->_tpl_vars['asterisk_config']['asterisk_relate_to_contact_enabled']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_relate_to_contact_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_relate_to_contact_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_relate_to_contact_enabled', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_relate_to_contact_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_relate_to_contact_enabled', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_relate_to_contact_enabled', $this->_tpl_vars['config']['asterisk_relate_to_contact_enabled']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_relate_to_contact_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_relate_to_contact_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_relate_to_contact_enabled', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_relate_to_contact_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_relate_to_contact_enabled', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_relate_to_contact_enabled' value='0'>
    <input type='checkbox' name='asterisk_relate_to_contact_enabled' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_relate_to_contact_enabled']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_relate_to_contact_enabled']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_relate_to_contact_enabled']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_relate_to_contact_enabled']; ?>
' -->
    </td>



<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CREATE_NEW_CONTACT_ENABLED']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CREATE_NEW_CONTACT_ENABLED_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CREATE_NEW_CONTACT_ENABLED_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_create_new_contact_enabled'] )): ?>
        <?php $this->assign('asterisk_create_new_contact_enabled', $this->_tpl_vars['asterisk_config']['asterisk_create_new_contact_enabled']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_create_new_contact_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_create_new_contact_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_create_new_contact_enabled', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_create_new_contact_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_create_new_contact_enabled', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_create_new_contact_enabled', $this->_tpl_vars['config']['asterisk_create_new_contact_enabled']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_create_new_contact_enabled'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_create_new_contact_enabled', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_create_new_contact_enabled', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_create_new_contact_enabled', ''); ?>
            <?php $this->assign('caseNumasterisk_create_new_contact_enabled', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_create_new_contact_enabled' value='0'>
    <input type='checkbox' name='asterisk_create_new_contact_enabled' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_create_new_contact_enabled']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_create_new_contact_enabled']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_create_new_contact_enabled']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_create_new_contact_enabled']; ?>
' -->
    </td>

<TD>&nbsp;</TD><TD>&nbsp;</TD> </tr>

<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Phone Fields</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CONTACT_PHONE_FIELDS']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CONTACT_PHONE_FIELDS_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CONTACT_PHONE_FIELDS_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_contact_phone_fields'] )): ?>
        <?php $this->assign('asterisk_contact_phone_fields', $this->_tpl_vars['asterisk_config']['asterisk_contact_phone_fields']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_contact_phone_fields', $this->_tpl_vars['config']['asterisk_contact_phone_fields']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_contact_phone_fields' size="45" value='<?php echo $this->_tpl_vars['asterisk_contact_phone_fields']; ?>
'>
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_ACCOUNT_PHONE_FIELDS']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_ACCOUNT_PHONE_FIELDS_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_ACCOUNT_PHONE_FIELDS_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">
    <?php if (empty ( $this->_tpl_vars['config']['asterisk_account_phone_fields'] )): ?>
        <?php $this->assign('asterisk_account_phone_fields', $this->_tpl_vars['asterisk_config']['asterisk_account_phone_fields']); ?>
    <?php else: ?>
        <?php $this->assign('asterisk_account_phone_fields', $this->_tpl_vars['config']['asterisk_account_phone_fields']); ?>
    <?php endif; ?>
        <input type='textbox' name='asterisk_account_phone_fields' size="45" value='<?php echo $this->_tpl_vars['asterisk_account_phone_fields']; ?>
'>
    </td>



<TR><td colspan="4">&nbsp;&nbsp;<TR><TD colspan="4"><h4>Developer</h4></TD></tr>


<TR>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALLINIZE_DEV']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CALLINIZE_DEV_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALLINIZE_DEV_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_callinize_dev'] )): ?>
        <?php $this->assign('asterisk_callinize_dev', $this->_tpl_vars['asterisk_config']['asterisk_callinize_dev']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_callinize_dev'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_callinize_dev', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_callinize_dev', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_callinize_dev', ''); ?>
            <?php $this->assign('caseNumasterisk_callinize_dev', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_callinize_dev', $this->_tpl_vars['config']['asterisk_callinize_dev']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_callinize_dev'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_callinize_dev', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_callinize_dev', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_callinize_dev', ''); ?>
            <?php $this->assign('caseNumasterisk_callinize_dev', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_callinize_dev' value='0'>
    <input type='checkbox' name='asterisk_callinize_dev' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_callinize_dev']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_callinize_dev']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_callinize_dev']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_callinize_dev']; ?>
' -->
    </td>

    <td nowrap width="10%" class="dataLabel"><?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALLINIZE_DEBUG']; ?>

      <?php if (! empty ( $this->_tpl_vars['MOD']['LBL_ASTERISK_CALLINIZE_DEBUG_DESC'] )): ?>
          [<a href="#" data-toggle="tooltip" title="<?php echo $this->_tpl_vars['MOD']['LBL_ASTERISK_CALLINIZE_DEBUG_DESC']; ?>
">?</a>]:
      <?php endif; ?>
    </td>
    <td width="25%" class="dataField">

    <?php if (empty ( $this->_tpl_vars['config']['asterisk_callinize_debug'] )): ?>
        <?php $this->assign('asterisk_callinize_debug', $this->_tpl_vars['asterisk_config']['asterisk_callinize_debug']); ?>
        <?php if ($this->_tpl_vars['asterisk_config']['asterisk_callinize_debug'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_callinize_debug', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_callinize_debug', "Case1a: Config not set, default value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_callinize_debug', ''); ?>
            <?php $this->assign('caseNumasterisk_callinize_debug', "CASE1b: Config not set, using default value = 0"); ?>
        <?php endif; ?>
    <?php else: ?>
        <?php $this->assign('asterisk_callinize_debug', $this->_tpl_vars['config']['asterisk_callinize_debug']); ?>
        <?php if ($this->_tpl_vars['config']['asterisk_callinize_debug'] == '1'): ?>
            <?php $this->assign('isCheckedasterisk_callinize_debug', 'checked'); ?>
            <?php $this->assign('caseNumasterisk_callinize_debug', "CASE2a: Config is set, value = 1"); ?>
        <?php else: ?>
            <?php $this->assign('isCheckedasterisk_callinize_debug', ''); ?>
            <?php $this->assign('caseNumasterisk_callinize_debug', "CASE2b: Config is set, value = 0"); ?>
        <?php endif; ?>
    <?php endif; ?>
    <input type='hidden' name='asterisk_callinize_debug' value='0'>
    <input type='checkbox' name='asterisk_callinize_debug' size="45" value='1' <?php echo $this->_tpl_vars['isCheckedasterisk_callinize_debug']; ?>
 >
    <!-- <?php echo $this->_tpl_vars['caseNumasterisk_callinize_debug']; ?>
 Config Val: '<?php echo $this->_tpl_vars['config']['asterisk_callinize_debug']; ?>
', default value: '<?php echo $this->_tpl_vars['asterisk_config']['asterisk_callinize_debug']; ?>
' -->
    </td>
